quarkus.kogito.devservices.enabled=false
quarkus.keycloak.devservices.enabled=false

kogito.events.grouping=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sonataflow
quarkus.datasource.password=sonataflow
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sonataflow

kie.flyway.enabled=true
quarkus.flyway.migrate-at-start=false

kafka.bootstrap.servers=localhost:19092

mp.messaging.outgoing.kogito-processinstances-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-processinstances-events.topic=kogito-processinstances-events
mp.messaging.outgoing.kogito-processinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.kogito-usertaskinstances-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-usertaskinstances-events.topic=kogito-usertaskinstances-events
mp.messaging.outgoing.kogito-usertaskinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.kogito-processdefinitions-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-processdefinitions-events.topic=kogito-processdefinitions-events
mp.messaging.outgoing.kogito-processdefinitions-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
